name: Build & release
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  BIN_NAME: Configurer.exe

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: set version in env
        id: get-version
        run: |
          ver=$(python -c "import src.configurer; print(src.configurer.__version__)")
          echo "version=$ver"
          echo "version=$ver" >> "$GITHUB_OUTPUT"

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: pip
    - name: Install dependencies
      run: |
        python -m venv env
        ./env/Scripts/Activate.ps1
        python -m pip install --upgrade pip
        python -m pip install .[build]
    - name: Build with pyinstaller
      run: |
        pyinstaller --clean configurer.spec
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: dist/${{ env.BIN_NAME }}
        compression-level: 0

  release:
    runs-on: ubuntu-latest
    needs:
      - get-version
      - build
    permissions:
      contents: write
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: executable
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: v${{ needs.get-version.outputs.version }}
          files: ${{ env.BIN_NAME }}
