name: Build & release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    outputs:
      bin_name: ${{ steps.pyinstaller.outputs.bin_name }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: pip
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install .[build]
    - name: Build with pyinstaller
      id: pyinstaller
      run: |
        pyinstaller --clean configurer.spec
        echo "bin_name=Configurer.exe" >> $GITHUB_OUTPUT
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: dist/$bin_name
        compression-level: 0

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: executable
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ${{ needs.build.outputs.bin_name }}
